FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Install nodemon untuk hot reload
RUN npm install -g nodemon prisma

# Jalankan script dev
CMD ["nodemon", "--env-file=.env.development", "src/index.js"]
